server:
  port: 8080
okta:
  oauth2:
    issuer: https://dev-460642.oktapreview.com/oauth2/default
    client-id: {indentificator-from-okta-dev-account}
    client-secret: {indentificator-from-okta-dev-account}
spring:
  thymeleaf:
    cache: false
